### ISSUE TITLE
security settings in cache UnkownUser role.

### ISSUE THREAD

**Issue by nlzv** [mariosanchez23/pButtons-Buttons-analyzer#1]
csp applications
/api/pButtons/
/pButtons
is not authentcated. But if UnknownUser has no any role then application does not work.
One of fix is assign UnknownUser %All role. 
But it might be not acceptable.
Another solution is to assign role %All to applications 
/api/pButtons/
/pButtons

**Comment by mariosanchez23** [comment]
Yep, 
It works like a normal web application. So adding the role or simply prompting for password for authenticate should work.
